### ISSUE TITLE
There was a problem opening that file

### ISSUE THREAD

**Issue by khajvahmac** [turtl/js#172]
I am getting this error when uploading relatively big files. About 6mb images/attachments don't open on a different device than the one used to upload. Is this a limitation in order to conserve space? Will this disappear if I host my own server.

Here is the error message:
`[5608:0608/231240:INFO:CONSOLE(200)] ""note: file: open: " "01553141b02523564cd0f9f5891664138f59ca1eba6173df70309aba5b3df38ef2fbdbb98c1501d8" "Error: file: to_array: file data not present\n    at null.\u003Canonymous\u003E (file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/models/file.js:77:12)\n    at tryCatch1 (file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/library/bluebird.js:5004:21)\n    at Promise$_callHandler [as _callHandler] (file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/library/bluebird.js:2562:13)\n    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/library/bluebird.js:2576:18)\n    at Promise$_settlePromiseAt [as _settlePromiseAt] (file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/library/bluebird.js:2739:14)\n    at Promise$_settlePromises [as _settlePromises] (file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/library/bluebird.js:2882:14)\n    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/library/bluebird.js:150:12)\n    at Async$consumeFunctionBuffer (file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/library/bluebird.js:113:14)\n    at process._tickCallback (node.js:375:11)"", source: file:///tmp/.org.chromium.Chromium.AWMKDd/data/app/controllers/notes/view.js (200)
`

**Comment by khajvahmac** [comment]
https://groups.google.com/forum/#!topic/turtl/EbugQ8gtSns 

Move to google group
